derhansen/sf_event_mgt

Configuration/FlexForms/Flexform_plugin.xml, Configuration/FlexForms/Flexform_userreg.xml, Configuration/TCA/tx_sfeventmgt_domain_model_event.php, Configuration/TCA/tx_sfeventmgt_domain_model_location.php, Configuration/TCA/tx_sfeventmgt_domain_model_organisator.php, Configuration/TCA/tx_sfeventmgt_domain_model_priceoption.php, Configuration/TCA/tx_sfeventmgt_domain_model_registration.php
This fixes issue with access tab not being rendered in the TYPO3 backend.
The old path has been deprecated in TYPO3 7.4 and is not working in 8.7.
=> Fix path to core language file locallang_ttc.xlf

Classes/Service/RegistrationService.php
The type of the param `$result` is declared as `RegistrationResult` while in fact the constants from that class are used to provide the status which is an integer.
=> Change type of param in doc header

Resources/Private/Templates/Notification/Admin/RegistrationCancelled.html, Resources/Private/Templates/Notification/Admin/RegistrationConfirmed.html, Resources/Private/Templates/Notification/Admin/RegistrationNew.html, Resources/Private/Templates/Notification/Admin/RegistrationWaitlistConfirmed.html, Resources/Private/Templates/Notification/Admin/RegistrationWaitlistNew.html
The error ```#1476107295: PHP Warning: htmlspecialchars() expects parameter 1 to be string, object given in /vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/EscapingNode.php line 44```
occurs in TYPO3 8.7. 
This patch uses the same syntax of the viewhelper as in formatting the event date in the file
=> [BUGFIX] Fix error while formatting dateOfBirth in T3 8.7

Configuration/TCA/tx_sfeventmgt_domain_model_event.php, Configuration/TCA/tx_sfeventmgt_domain_model_organisator.php, Configuration/TCA/tx_sfeventmgt_domain_model_speaker.php
As support for TYPO3 7.6 was removed in b0b0d5e0ba35f558d8a2ab91a53edd63aefb309a the foreign_key is not longer necessary and can be removed.
=> [TASK] Remove foreign_types from TCA

Classes/Domain/Repository/RegistrationRepository.php
You have a line of code that is used twice in the same instruction. This pull request removes one of those lines.
=> remove duplicate code

Classes/Controller/EventController.php
Pass $failed variable explicitly to the confirmation template. Without this it's only possible to get the confirmation status implicitly, if no $event is available in the template.
It can be used to style the output, so a user can get the result of the action easier, e.g. with a callout
Affected templates:
- ConfirmRegistration
- CancelRegistration
=> [Task] Pass "failed" variable explicitly to the template

Classes/DataProcessing/DisableLanguageMenuProcessor.php, Classes/Utility/EventAvailability.php, Documentation/ForAdministrators/Seo/Index.rst, Documentation/ForAdministrators/Seo/LanguageMenu/Index.rst
The DataProcessor is to be used on detail pages and disables languages
which are in languageMode=strict and not having a translation for the
current event.
Basically a copy from EXT:news
Relates: #817
=> [FEATURE] Add DataProcessor for language navigations

Classes/Hooks/DataHandlerHooks.php
The fields were always saved to flexform, thus their subject was empty
=> [BUGFIX] Allow overwrite subject of waitlist moveup mail

ext_tables.sql
In general every query using a where clause should use an index for better performance
=> Add DB indices for 1:n inline relations

Classes/Hooks/DataHandlerHooks.php
Currently they remain in the db when deleting an event.
=> Delete custom notifications when deleting an event

Classes/Service/RegistrationService.php, Resources/Private/Language/locallang.xlf
This prevents 'Call to a member function getEnableCancel() on null'
=> [BUGFIX] Handle non-existent event in checkCancelRegistration()

Classes/ViewHelpers/Format/ICalendarDescriptionViewHelper.php
Without this fix the iCal description is not multibyte character aware.
This results in multibyte character-splitting at line ends:
```text
bei schwerer betroffenen Erkrankten viel Positives bewirken und ein gröÍ
tmögliches Maß an Beweglichkeit erhalten. Viele Beispiele und wissensch
```
By wrongly splitting multibyte chars, the Gnome Linux Desktop does not recognize the iCal entry and fails. On other systems e.g. Android with Google calendar the text is displayed broken.
---
As of [RFC5545 Section 3.1](https://www.rfc-editor.org/rfc/rfc5545#section-3.1):
"Lines of text SHOULD NOT be longer than 75 octets, excluding the line break."
– So having less octets/bytes is fine as well.
With multibyte characters I made this assumption for description text:
`In worst case there are a max of 2 …
=> [BUGFIX] handle multibyte characters in iCal description

Resources/Private/Language/locallang_db.xlf
As there is one label missing in the event registration I added it. Hope the label is fine like that!
=> [BUGFIX] Add missing tab label for event registration in backend

Classes/Domain/Repository/RegistrationRepository.php
The plugin `Pieventregistration` and its `listAction` are able to have `displayMode` configured as `current_future` which should list current & future events user has registered for. Because the case `current_future` is missing within `RegistrationRepository` all events are listed in that case because no constraint was being built.
=> [BUGFIX] DisplayMode 'current_future' was not implemented within RegistrationRepository

Documentation/BreakingChanges/Index.rst
In documentation the path to new TypoScript setting was not 100% correct ;-)
=> [BUGFIX] Wrong TypoScript path in documentation for migration (plugin.tx_sfeventmgt.settings)

Classes/ViewHelpers/Registration/IsRequiredFieldViewHelper.php
The function `explode` must use a string as fallback
=> [BUGFIX] Default value must be a string

Configuration/TCA/tx_sfeventmgt_domain_model_event.php, Configuration/TCA/tx_sfeventmgt_domain_model_location.php, Configuration/TCA/tx_sfeventmgt_domain_model_organisator.php, Configuration/TCA/tx_sfeventmgt_domain_model_priceoption.php, Configuration/TCA/tx_sfeventmgt_domain_model_registration_field.php, Configuration/TCA/tx_sfeventmgt_domain_model_speaker.php
The field doesn't have any use anymore since 2019, see https://review.typo3.org/c/Packages/TYPO3.CMS/+/59297/ and furtheremore a notice is removed if an event is moved via clipboard
=> [TASK] Remove t3ver_label field from TCA

Classes/Controller/EventController.php
Added a missing dispatch statement for ProcessRedirectToPaymentEvent. This fixes issue #1114 for v6.x (TYPO3 v11)
=> Add dispatch for ProcessRedirectToPaymentEvent

Classes/Updates/PiEventPluginUpdater.php
Correct use for INSERT, UPDATE and DELETE queries is executeStatement(). When using executeQuery(), you get an error: "Cannot access offset of type string on string" at typo3/cms-core/Classes/Database/Query/QueryBuilder.php line 1314
=> [BUGFIX] use correct execute method for update statement

Classes/Controller/AdministrationController.php, Classes/Event/ModifyAdministrationIndexNotifyViewVariablesEvent.php, Classes/Event/ModifyAdministrationListViewVariablesEvent.php, Tests/Unit/Controller/AdministrationControllerTest.php
Would be nice to have events similar to the EventController in the AdministratorController.
In my case it was requested to show events recursively from all child folders, which could be realized with the newly added events without having to use XCLASSes.
=> [FEATURE] Added PSR-14 events to modify variables for administration module

Classes/Controller/EventController.php
`$this->settings['disableOverrideDemand']` ist type string, this method returns always true, while this setting enabled (value '1'), override demand was not disabled.
=> [BUGFIX] Fix: setting disableOverrideDemand not working

Classes/Service/RegistrationService.php
The client uses the backend to add additional registrations. Because of this, the count of free places becomes not 0 but negative. because of the wrong check this leads to the bug that *all* valid waiting list registrations are moved from the waiting list to the regular list
=> [BUGFIX] Fix wrong check for waitlist moval

Classes/Service/CalendarService.php
When browsing the calendar by week, I get the wrong year after calendar week 52. It gives me the year 2024 instead of 2025.
https://github.com/derhansen/sf_event_mgt/blob/5fa7286da7f370934b5c7bba5d941e14dcb80bcf/Resources/Private/Templates/Event/Calendar.html#L11-L34
Debugging `$firstDayNextWeek` gives me `2024-12-30` which results in "2024" for the parameter `tx_sfeventmgt_pieventcalendar[overwriteDemand][year]=2024` but it should be 2025.
https://github.com/derhansen/sf_event_mgt/blob/5fa7286da7f370934b5c7bba5d941e14dcb80bcf/Classes/Service/CalendarService.php#L163
This pull request addresses this issue, by using the parameter `o` for formatting the year.
The PHP manual states for the parameter the following:
ISO 8601 week-numbering year. This has the same value as Y, except that if the …
=> [BUGFIX] Get correct year for weekConfig. Use ISO 8601 week-numbering year
